{%set name = "pycandela" %}
{%set version = "0.4.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "cbbf19931f762afbcdfa682f09ec43284788a1908e5d3ca3b3b8faaff9185280" %}
{%set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install

requirements:
  build:
    - python
    - jupyter
    - pandas

  run:
    - python
    - jupyter
    - pandas

test:
  files:
    - run_test.sh

about:
  home: https://github.com/Kitware/candela
  # license file is kept in a higher-level directory for Candela as a whole
  # we link a copy here
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  license: Apache 2.0
  summary: 'Jupyter interface for Candela visualization components'
  doc_url: https://candela.readthedocs.io/
  dev_url: https://github.com/Kitware/candela

extra:
  recipe-maintainers:
    - pmlandwehr
