travis:
  secure:
    BINSTAR_TOKEN: kfGSrxNN8KW1nxYV2Nwrnu5HYobvT73/HXOtuIOw+4i7a79ZOjaK3M5gRxsT5YtYJq/GJ3zdQFBbvyxSzlITvycJJ9jZJ05ua2Q66g/YOY1h5uPP6QyM9p2usO/9N385YsCxsNKvbhXb3sKICy3ml8p9fW6n6MeGnBkgTcxmOQCvykR+TCfSYYzy9QU5jOp1blg2qqscPa05Jjmp8IYDvWOsrCUtt0NFcUd5m3u0qltFBxoyTale/whBfTnBJgEdWjbmVui5Z7W2TAPyJdLwcgq2/G7139CFKpZG5voXz6K/Koy/Jh/VXkYBn98eoD0eeZf5Cblb0drx0/Kd9YerZNQvy5UP1h1YVU4iFvJApSlBdk+LZJNhZLb1CtqnPmtheDHef1eTBVeNhSz77+48ScYDxGx7CdQOXk7f6/THcvJbH4fijX9zjI/Zie9YjnaB76GEZRP+9j0cTCbiwK9rYE9FdB1CVZTwIS7PkmU9FYUj+pKSF+wRFplcGQs5Vt0z8a45E1mHqtYlXfK98Im4cLMqpOX17uqgSDQST7kQjco5oy7jXKu3B6Agdua6oM1AgGFPDgB2qF82o1tu01ctKGTi00kaLD8qeUw/zissP5eR15rUFZJ5Pr+DG8OdpVmuBGYsLOki932Atx/sCJ7o0UDtW8bBNWgMbszur6GK8gs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
