travis:
  secure:
    BINSTAR_TOKEN: mop1drLWK5XkD1LN1CRxqUcYcJ4bWmidS8Dm79DQrpiUBUc/c+6oastOdbtIADQrEr8VF3qyz61ASHXfbFI7XNbGy5LbGzVrlJwC+D/GS3/CU3lwfLhcqyO7b0uFAqiQcH/ciUfIhDixEILZqmTfwRThmNd08KomDm52M00K0H4seKkpnY0rUnaGy5UxWRoOTCwSWDNpQawe7d/yH9Zk8dn9C9KwR7ZEXo9Oxm4fonlQYq7GlULNADEDvK74JZCaGx4Y/hxEgqx78bk06mpq0Qn9YERWApUzyytc6W8LWyFV7N9+N8FWMSXf3nQ/wKy14GHZg9YuFiQH5yjeV7iVcb8bWrjrjWaL68t3Gya1chkmezeRw3aV3YCIB1BQEJtnqRLRR0fxftaMLasY4Oi10pcv2zIK0YUzMzoDjXk5t9eu3cQg8BpeNjZnCQWKP8oJT8/jMdzmuMS2q3nFvy7/AuG4XeGRgM/BVnjrSuKWZMpwOy3P3bAEmI78rYUcgWagZ5q94F+7tfUqo5whsdJRQ/tEiVs7MdTNEkLFwLjhb2iVCCAqGn6hZI5d2pWrLE4KNkqtZErn3Fku8gCe6Cnc918Y5z6f9OKMSVWbzuagZTY/tviG/MS3GT6IZUV9Kb3oKYMdf9tKovtb5HpkKNPx4UlbUY/Ksgt0PKTEZ0Yyec4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
